import { HeatmapDay, TodayHabit } from './home-summary.model';
import { DebtApi } from './debts.model';
import { RecurringPayment } from './recurring-payment.model';
import { SavingsGoalApi } from './savings.model';

export interface DashboardSummary {
  userName?: string;
  date?: string;
  availableToday?: string | number;
  resetHours?: string | number;
  weeklySpent?: string | number;
  weeklyRemaining?: string | number;
  weeklyLimit?: string | number;
  monthlySpent?: string | number;
  monthlyLimit?: string | number;
  saved?: string | number;
  savingsCurrent?: string | number;
  savingsLabel?: string;
  debtLeft?: string | number;
  debtLabel?: string;
  nextDebtDate?: string;
  nextDebtPayment?: string | number;
  debtProgress?: string | number;
  suggestedExtraPayment?: string | number;
  periodIncome?: string | number;
  periodSpent?: string | number;
  budgetRemaining?: string | number;
  currentMonthExpenses?: string | number;
  currentWeekExpenses?: string | number;
  totalDebt?: string | number;
  totalSavingsGoal?: string | number;
  upcomingPayments?: RecurringPayment[];
  activeDebts?: DebtApi[];
  activeSavingsGoals?: SavingsGoalApi[];
  habitsToday?: TodayHabit[];
  activeDays?: string | number;
  streak?: string | number;
  habits?: TodayHabit[];
  heatmap?: HeatmapDay[];
  [key: string]: unknown;
}
